universe			= vanilla
log				= /home/mwolff3/submitted/logs/test_filtering_$(Cluster).log
error				= /home/mwolff3/submitted/errs/test_filtering_$(Cluster).err
output				= /home/mwolff3/submitted/output/test_filtering_$(Cluster).out
executable			= /home/mwolff3/desman_scripts/test_filtering.sh
arguments			= $(Process)
# transfer_input_files 	=  # unused bc we're using Gluster

# IMPORTANT! Require execute servers that have Gluster:
Requirements		= (Target.HasGluster == true)
should_transfer_files	= YES
when_to_transfer_output	= ON_EXIT

# computational resources for each job
request_cpus		= 3
request_memory		= 10GB
request_disk		= 40GB

queue
